dist:     trusty    # ���������� Ubuntu 14.04 Trusty Tahr (� �� 12.02 Precise Pangolin)
sudo:     required  # ���������� Virtual Machine (� �� Docker container)

language: cpp       # �� �������� ������� ����� ����������� ��� C++ ����������
                    # �, ������, python -- �������. �� ����� ����� cpp.

os:
    # ����� ��������� CI � �� Linux, � �� Mac OS X...
    - linux
    - osx

compiler:
    # ... � � ������� GCC, � Clang
    - gcc
    - clang

env:
    # ������ ���������� ���������, �������� �� ������� ������:
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Release

matrix:
    exclude:
        # ������� �������� �������� �������� �� ������� ������:
        - os:       osx
          compiler: gcc

        - os:  osx
          env: TARGET_CPU=x86 BUILD_CONFIGURATION=Debug

        - os:  osx
          env: TARGET_CPU=x86 BUILD_CONFIGURATION=Release

before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX

install: skip
    # ������ ��������� ����� � ��������� ������������:
#    - source ci/travis/install-$TRAVIS_OS_NAME.sh

script:
    # ������ ������ � ������������ �������:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
    - cmake --build .
    - ctest --output-on-failure

deploy:
    # ����������� tagged-������� �� GitHub Releases:
    provider:     releases
    file:         <package-file>
    skip_cleanup: true
    overwrite:    true

    api_key:
        secure:   <encrypted-github-token>

    on:
        tags:     true